let leds_neopixel = probots.newStripNeopixel(probots.brickPort(ConnectionPorts.CON2), 8)
basic.forever(function () {
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.Violet)
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.Black)
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.Yellow)
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.Black)
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.White)
    basic.pause(1000)
    probots.showColor(leds_neopixel, Colors.Black)
})