basic.forever(function () {
    probots.ledOn(probots.brickPort(ConnectionPorts.CON6))
    basic.pause(500)
    probots.ledOff(probots.brickPort(ConnectionPorts.CON6))
    basic.pause(100)
    probots.ledOnWithPower(probots.brickPort(ConnectionPorts.CON6),5)
    basic.pause(500)
    probots.ledOff(probots.brickPort(ConnectionPorts.CON6))
    basic.pause(100)
})